/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderSuccessOrderIdRouteImport } from './routes/order-success.$orderId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminWebOrdersRouteImport } from './routes/admin.web-orders'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCancelledOrdersRouteImport } from './routes/admin.cancelled-orders'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAccountingRouteImport } from './routes/admin.accounting'
import { Route as AdminFinanceTransactionsRouteImport } from './routes/admin.finance.transactions'
import { Route as AdminFinanceSettlementsRouteImport } from './routes/admin.finance.settlements'
import { Route as AdminFinanceOrdersPnlRouteImport } from './routes/admin.finance.orders-pnl'
import { Route as AdminFinanceAccountsRouteImport } from './routes/admin.finance.accounts'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessOrderIdRoute = OrderSuccessOrderIdRouteImport.update({
  id: '/order-success/$orderId',
  path: '/order-success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebOrdersRoute = AdminWebOrdersRouteImport.update({
  id: '/web-orders',
  path: '/web-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCancelledOrdersRoute = AdminCancelledOrdersRouteImport.update({
  id: '/cancelled-orders',
  path: '/cancelled-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingRoute = AdminAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceTransactionsRoute =
  AdminFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminFinanceRoute,
  } as any)
const AdminFinanceSettlementsRoute = AdminFinanceSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceOrdersPnlRoute = AdminFinanceOrdersPnlRouteImport.update({
  id: '/orders-pnl',
  path: '/orders-pnl',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceAccountsRoute = AdminFinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminFinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cancelled-orders': typeof AdminCancelledOrdersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/web-orders': typeof AdminWebOrdersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/finance/accounts': typeof AdminFinanceAccountsRoute
  '/admin/finance/orders-pnl': typeof AdminFinanceOrdersPnlRoute
  '/admin/finance/settlements': typeof AdminFinanceSettlementsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cancelled-orders': typeof AdminCancelledOrdersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/web-orders': typeof AdminWebOrdersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/track': typeof TrackIndexRoute
  '/admin/finance/accounts': typeof AdminFinanceAccountsRoute
  '/admin/finance/orders-pnl': typeof AdminFinanceOrdersPnlRoute
  '/admin/finance/settlements': typeof AdminFinanceSettlementsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cancelled-orders': typeof AdminCancelledOrdersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/web-orders': typeof AdminWebOrdersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/finance/accounts': typeof AdminFinanceAccountsRoute
  '/admin/finance/orders-pnl': typeof AdminFinanceOrdersPnlRoute
  '/admin/finance/settlements': typeof AdminFinanceSettlementsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/request'
    | '/reset-password'
    | '/returns'
    | '/robots.txt'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin/accounting'
    | '/admin/analytics'
    | '/admin/cancelled-orders'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/finance'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/web-orders'
    | '/category/$slug'
    | '/order-success/$orderId'
    | '/product/$id'
    | '/track/$orderId'
    | '/admin/'
    | '/track/'
    | '/admin/finance/accounts'
    | '/admin/finance/orders-pnl'
    | '/admin/finance/settlements'
    | '/admin/finance/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/request'
    | '/reset-password'
    | '/returns'
    | '/robots.txt'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin/accounting'
    | '/admin/analytics'
    | '/admin/cancelled-orders'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/finance'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/web-orders'
    | '/category/$slug'
    | '/order-success/$orderId'
    | '/product/$id'
    | '/track/$orderId'
    | '/admin'
    | '/track'
    | '/admin/finance/accounts'
    | '/admin/finance/orders-pnl'
    | '/admin/finance/settlements'
    | '/admin/finance/transactions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/request'
    | '/reset-password'
    | '/returns'
    | '/robots.txt'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin/accounting'
    | '/admin/analytics'
    | '/admin/cancelled-orders'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/finance'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/web-orders'
    | '/category/$slug'
    | '/order-success/$orderId'
    | '/product/$id'
    | '/track/$orderId'
    | '/admin/'
    | '/track/'
    | '/admin/finance/accounts'
    | '/admin/finance/orders-pnl'
    | '/admin/finance/settlements'
    | '/admin/finance/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrderSuccessOrderIdRoute: typeof OrderSuccessOrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  TrackIndexRoute: typeof TrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$orderId': {
      id: '/order-success/$orderId'
      path: '/order-success/$orderId'
      fullPath: '/order-success/$orderId'
      preLoaderRoute: typeof OrderSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/web-orders': {
      id: '/admin/web-orders'
      path: '/web-orders'
      fullPath: '/admin/web-orders'
      preLoaderRoute: typeof AdminWebOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cancelled-orders': {
      id: '/admin/cancelled-orders'
      path: '/cancelled-orders'
      fullPath: '/admin/cancelled-orders'
      preLoaderRoute: typeof AdminCancelledOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting': {
      id: '/admin/accounting'
      path: '/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AdminAccountingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/transactions': {
      id: '/admin/finance/transactions'
      path: '/transactions'
      fullPath: '/admin/finance/transactions'
      preLoaderRoute: typeof AdminFinanceTransactionsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/settlements': {
      id: '/admin/finance/settlements'
      path: '/settlements'
      fullPath: '/admin/finance/settlements'
      preLoaderRoute: typeof AdminFinanceSettlementsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/orders-pnl': {
      id: '/admin/finance/orders-pnl'
      path: '/orders-pnl'
      fullPath: '/admin/finance/orders-pnl'
      preLoaderRoute: typeof AdminFinanceOrdersPnlRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/accounts': {
      id: '/admin/finance/accounts'
      path: '/accounts'
      fullPath: '/admin/finance/accounts'
      preLoaderRoute: typeof AdminFinanceAccountsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
  }
}

interface AdminFinanceRouteChildren {
  AdminFinanceAccountsRoute: typeof AdminFinanceAccountsRoute
  AdminFinanceOrdersPnlRoute: typeof AdminFinanceOrdersPnlRoute
  AdminFinanceSettlementsRoute: typeof AdminFinanceSettlementsRoute
  AdminFinanceTransactionsRoute: typeof AdminFinanceTransactionsRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinanceAccountsRoute: AdminFinanceAccountsRoute,
  AdminFinanceOrdersPnlRoute: AdminFinanceOrdersPnlRoute,
  AdminFinanceSettlementsRoute: AdminFinanceSettlementsRoute,
  AdminFinanceTransactionsRoute: AdminFinanceTransactionsRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountingRoute: typeof AdminAccountingRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCancelledOrdersRoute: typeof AdminCancelledOrdersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminWebOrdersRoute: typeof AdminWebOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountingRoute: AdminAccountingRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCancelledOrdersRoute: AdminCancelledOrdersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminWebOrdersRoute: AdminWebOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrderSuccessOrderIdRoute: OrderSuccessOrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  TrackIndexRoute: TrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
