// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgsspipkjeuceftuatue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnc3NwaXBramV1Y2VmdHVhdHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNDcyMzIsImV4cCI6MjA5MTgyMzIzMn0.h6aRTBUhTvEvKCx8M-lvyA2BCBQbhvWMWKgn8dIyilc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowserRuntime =
  typeof document !== "undefined" && typeof globalThis.localStorage !== "undefined";

const browserLocalStorage = {
  getItem(key: string) {
    if (!isBrowserRuntime) return null;
    return globalThis.localStorage.getItem(key);
  },
  setItem(key: string, value: string) {
    if (!isBrowserRuntime) return;
    globalThis.localStorage.setItem(key, value);
  },
  removeItem(key: string) {
    if (!isBrowserRuntime) return;
    globalThis.localStorage.removeItem(key);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserLocalStorage,
    persistSession: isBrowserRuntime,
    autoRefreshToken: isBrowserRuntime,
  }
});

const CLIENT_SESSION_KEY = "hs_client_sid";

export function getClientSessionId(): string {
  if (typeof window === "undefined") return "";
  try {
    let sid = window.sessionStorage.getItem(CLIENT_SESSION_KEY);
    if (!sid) {
      sid = crypto.randomUUID();
      window.sessionStorage.setItem(CLIENT_SESSION_KEY, sid);
    }
    return sid;
  } catch {
    return crypto.randomUUID();
  }
}